### PR TITLE
Fix index not being used when hasLabel step has multiple labels

### LINKED ISSUE #124: Index is not used when hasLabel step has multiple labels
In `OrientGraphStep.findIndex()`, since values iterator is created before class labels loop, it is iterated only for the first label and, for all the others, full index is queried from the DB.

### PR DESCRIPTION
**Pull request by ddrozdov**
This fixes #124.

### CODE REVIEW

**Comment by maggiolo00** [comment]
hi @ddrozdov 

thanks for this PR,
i will review it shortly. Do you have also a test case that fails with multiple label?

Enrico

**Comment by ddrozdov** [comment]
Hi @maggiolo00 

No, I don't have a test case for this and, in fact, the test wouldn't fail, there would just be a huge performance penalty since a lot of extra data would be loaded to the client.

**Comment by maggiolo00** [comment]
@ddrozdov 
ok if you have a snippet that reproduce the issue  just paste it here
I will eventually try to turn  it in a test case

Thanks

**Comment by maggiolo00** [comment]
Thanks @ddrozdov

**Pull request merged**
